### ISSUE TITLE
cron argument does not work

### ISSUE THREAD

**Issue by vijayshamdas** [MartineauUK/Chk-WAN#1]
Found a bug in cron section of args parsing - using cron argument does not produce cron entry  

Line 288 currently reads:

                if [ -n "$(cru l | grep "$0")" ];then

It should instead read:

                if [ -z "$(cru l | grep "$0")" ];then

Tested the fix on Merlin RT-AC68U, but should work equally well on any

**Comment by MartineauUK** [comment]
Fixed in **v1.15**
