### ISSUE TITLE
Inconsistency between doc, comment , and implementation on cron

### ISSUE THREAD

**Issue by H3llK33p3r** [MartineauUK/Chk-WAN#3]
Hi, If I well understand the help says : 

` ChkWAN  cron Will REBOOT router if the PINGs to ALL of the hosts FAILS, cron entry is added: Runs every 5mins.
'cru a ChkWAN "*/5 * * * * /jffs/scripts/ChkWAN.sh"'`

But the cron added is  (line 287): 

```bash
	if [ "$(echo $@ | grep -cw 'cron')" -gt 0 ];then
		if [ -n "$(cru l | grep "$0")" ];then
			CRON_ARGS=$(echo $@ | sed -e 's/\<cron\>//g')	# Strip 'cron' from being passed to the cru entry
			cru d Wan_Check
			cru a Wan_Check "*/30 0 * * * /jffs/scripts/$0 $CRON_ARGS"		# Every 30 mins on the half hour
			CRONJOB=$(cru l | grep "$0")
			Say "ChkWAN scheduled by cron"
			echo -e "$CRONJOB"
		fi
	fi
```

So implementation is not every 5 mins, not  'Every 30 mins on the half hour' but Every 30 mins on the half hour at midnight.

**Comment by MartineauUK** [comment]
Fix v1.15
