### ISSUE TITLE
Tries to ping 0.0.0.0 when used on N66U in AP mode

### ISSUE THREAD

**Issue by alexhk** [MartineauUK/Chk-WAN#5]
Hi  MartineauUK , thanks for your script, installed it successfully on a couple of AC86U and now on a N66U in AP mode.

I noticed it tries to ping 0.0.0.0 on the N66U in AP mode and wanted to report it quickly.

The firmware on the N66U is 374.43_44EAj9527 (Merlin LTS fork).

```
/jffs/scripts/ChkWAN.sh once nowait

(ChkWAN.sh): 942 v1.15 Monitoring WAN connection using 3 target PING hosts (0.0.0.0 9.9.9.9 1.1.1.1) (Tries=3)

(ChkWAN.sh): 942 Monitoring pass 1 out of 3

(ChkWAN.sh): 942 v1.15 Monitoring WAN connection using PING method to 0.0.0.0 check FAILED

(ChkWAN.sh): 942 Monitoring WAN connection OK.....(Successful ping to '9.9.9.9').
```
Not that it would matter much if used as is, but I just wanted to make you aware.

**Comment by MartineauUK** [comment]
Fixed.
Many thanks
